---
version: 2.2
project_name: license-manager

before:
    hooks:
        - go mod tidy

builds:
    - env:
          - CGO_ENABLED=0
      goos:
          - linux
          - windows
          - darwin
      goarch:
          - amd64
          - arm64
      main: ./cmd/license-manager
      ldflags:
          - >-
            -s -w   -X github.com/jeeftor/license-manager/cmd.buildVersion={{.Version}}   -X github.com/jeeftor/license-manager/cmd.buildCommit={{.ShortCommit}}   -X
            github.com/jeeftor/license-manager/cmd.buildTime={{.Timestamp}}
#
      binary: license-manager

archives:
    - formats:
          - tar.gz
      name_template: >-
          {{ .ProjectName }}_
          {{- title .Os }}_
          {{- if eq .Arch "amd64" }}x86_64
          {{- else if eq .Arch "386" }}i386
          {{- else }}{{ .Arch }}{{ end }}
      format_overrides:
          - goos: windows
            formats:
                - zip
      files:
          - README.md
          - LICENSE*
          - CHANGELOG*

sboms:
    - id: source-sbom
      artifacts: source
      documents:
          - '{{ .ProjectName }}_{{ .Version }}_source.sbom.cyclonedx.json'
      cmd: syft
      args:
          - . # Changed from dir:. to just .
          - -o
          - cyclonedx-json={{ .Document }} # Changed to cyclonedx-json to match your requested output file
          - --source-name={{ .ProjectName }}
          - --source-version={{ .Version }}
      env:
          - SYFT_FILE_METADATA_CATALOGER_ENABLED=true
          - SYFT_GO_CATALOGER_ENABLED=true
          - SYFT_PACKAGE_CATALOGER_ENABLED=true
nfpms:
    - package_name: license-manager
      vendor: jeeftor
      homepage: https://github.com/jeeftor/license-manager
      maintainer: Jeff Stein <jeffstein@gmail.com>
      description: License Manager Tool
      license: MIT
      formats:
          - deb
          - rpm
          - apk
      dependencies:
          - git
      contents:
          - src: ./LICENSE
            dst: /usr/share/doc/license-manager/LICENSE
          - src: ./README.md
            dst: /usr/share/doc/license-manager/README.md
      file_name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'



#      repository:
#        apt:
#          name: license-manager
#          owner: jeeftor
#          urls:
#            - 'https://apt.fury.io/jeeftor/'

publishers:
    - name: github
      ids: ['*']  # Publishes all artifacts

brews:
    - name: license-manager
      repository:
          owner: jeeftor
          name: homebrew-tap
      directory: Formula
      homepage: https://github.com/jeeftor/license-manager
      description: License Manager Tool
      license: MIT
      test: |
          system "#{bin}/license-manager version -s"
      install: |
          bin.install "license-manager"

checksum:
    name_template: checksums.txt

snapshot:
    version_template: '{{ incpatch .Version }}-next'

changelog:
    sort: asc
    filters:
        exclude:
            - '^docs:'
            - '^test:'
            - '^ci:'
            - '^chore:'
            - Merge pull request
            - Merge branch

release:
    github:
        owner: jeeftor
        name: license-manager
    draft: false
    prerelease: auto
    mode: replace
    header: |
        ## Release Notes
        For full details, see the [CHANGELOG.md](CHANGELOG.md).
    footer: |
        ## Thanks!
        Thanks to all contributors who helped make this release possible.
    name_template: v{{ .Version }}
