---
name: Pre-commit 🔎️
on:
    pull_request:
    push:
        branches:
            - master # or main, depending on your default branch
        tags-ignore:
            - v*  # ignore version tags
jobs:
    pre-commit:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - uses: actions/setup-go@v4
              with:
                  go-version: stable
            - name: Install Go dependencies
              run: go mod tidy

            - name: Install Go tools
              run: |
                  go install golang.org/x/tools/cmd/goimports@latest
                  go install mvdan.cc/gofumpt@latest
                  go install github.com/segmentio/golines@latest
                  go install github.com/goreleaser/goreleaser/v2@latest
            - name: Set up Python
              uses: actions/setup-python@v4
            - name: Install pre-commit
              run: pip install pre-commit
            - name: Run pre-commit
              run: pre-commit run --all-files --show-diff-on-failure
              env:
                  SKIP: no-commit-to-branch
                  TERM: xterm-256color
                  PRE_COMMIT_COLOR: always
                  ACTIONS_STEP_DEBUG: true
