name: Release
on:
  workflow_run:
    workflows: ["Pre-commit"]
    types:
      - completed
  push:
    tags:
      - 'v*'
permissions:
  contents: write
jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Debug conditions
        run: |
          echo "Event name: ${{ github.event_name }}"
          echo "Workflow run conclusion: ${{ github.event.workflow_run.conclusion }}"
          echo "Workflow run head branch: ${{ github.event.workflow_run.head_branch }}"
          echo "Ref: ${{ github.ref }}"
          echo "All conditions:"
          echo "1. workflow_run.conclusion == success: ${{ github.event.workflow_run.conclusion == 'success' }}"
          echo "2. head_branch == master: ${{ github.event.workflow_run.head_branch == 'master' }}"
          echo "3. event_name == push: ${{ github.event_name == 'push' }}"
          echo "4. ref starts with v: ${{ startsWith(github.ref, 'refs/tags/v') }}"

  release:
    needs: debug
    if: |
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.head_branch == 'master' &&
      github.event_name == 'push' &&
      startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v4
        with:
          go-version: 'stable'
      - uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
