name: Release
on:
  workflow_run:
    workflows: ["Pre-commit"]
    types:
      - completed
permissions:
  contents: write
jobs:
  release:
    if: |
      github.event.workflow_run.conclusion == 'success' &&
      github.ref_name == 'master' &&
      startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v4
        with:
          go-version: 'stable'

      - uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
